version: '3.7'

services:
  now_playing_dev:
    container_name: now_playing_dev
    build: ./
    restart: always
    env_file: .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: